---
# ansible-playbook -e "RANCHER_PROJECT_NAME=infrastructure" -i provision/scaleworks provision/cleanup.yml
- hosts: common
  gather_facts: yes
  tasks:
    - name: stop all docker containers
      shell: docker stop $(docker ps -a -q)
      ignore_errors: true
      become: yes
    - name: remove all docker containers
      shell: docker rm $(docker ps -a -q)
      ignore_errors: true
      become: yes
    - name: remove all docker images
      shell: docker rmi -f $(docker images -q)
      ignore_errors: true
      become: yes
    - name: remove all volumes
      shell: docker volume rm $(docker volume ls -qf dangling=true)
      ignore_errors: true
      become: yes
    - name: remove all volumes
      shell: rm -rf /data/lib/mysql
      ignore_errors: true
      become: yes

- hosts: masters
  gather_facts: yes
  tasks:
    - name: stop all docker containers
      shell: docker stop $(docker ps -a -q)
      ignore_errors: true
      become: yes
    - name: remove all docker containers
      shell: docker rm $(docker ps -a -q)
      ignore_errors: true
      become: yes
    - name: remove all docker images
      shell: docker rmi -f $(docker images -q)
      ignore_errors: true
      become: yes
    - name: remove all volumes
      shell: docker volume rm $(docker volume ls -qf dangling=true)
      ignore_errors: true
      become: yes
