---
# ansible-playbook -i provision/scaleworks provision/patch.yml
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: "configure cron"
      cron:
        name: "reboot"
        hour: "5"
        user: root
        job: "reboot"
