---
- name: create rancher-nginx directory
  file:
    path: "/data/etc/nginx"
    state: "directory"
    owner: 200
    group: root
  become: yes

- name: generate rancher-nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/data/etc/nginx/nginx.conf"
  become: yes

- name: start rancher-nginx container
  docker_container:
    name: "rancher-nginx"
    image: "nginx:stable"
    ports:
      - "8080:8080"
    volumes:
      - "/data/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart_policy: unless-stopped
  become: yes
