---
- name: start mysql server container
  docker_container:
    name: "{{ rancher_mysql_name }}"
    image: "{{ rancher_mysql_image }}:{{ rancher_mysql_version }}"
    ports:
      - "{{ rancher_mysql_port }}:3306"
    volumes:
      - "{{ rancher_mysql_data_dir }}:/var/lib/mysql"
    env:
      MYSQL_USER="{{ rancher_mysql_user }}"
      MYSQL_PASSWORD="{{ rancher_mysql_pass }}"
      MYSQL_DATABASE="{{ rancher_mysql_database }}"
      MYSQL_ROOT_PASSWORD="{{ rancher_mysql_rootpass }}"
    restart_policy: unless-stopped
  become: yes
